//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPUESTO
    {
        public int idrepuesto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public decimal precio_u { get; set; }
        public string estado { get; set; }
        public Nullable<int> idproveedor { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
